Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2020-10, with the labels that each got.

#16 Fixing the gradle dependencies.
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-16

#15 Remove unnecessary TF code
  .DS_Store
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-15

#17 Remove commented TF code
  infrastructure/main.tf
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-17

#11 AM-1013:Junit testing
  build.gradle
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/ActorIdType.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/Classification.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/GrantType.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/RoleCategory.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/RoleType.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/domain/model/enums/Status.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/DeleteExpiredRecords.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/RoleAssignmentHistory.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/util/BatchUtil.java
  src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/helper/TestDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/task/DeleteExpiredRecordsTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/task/RoleAssignmentHistoryTest.java
  src/test/resources/attributes.json
  src/test/resources/notes.json
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-11

#14 Added the necessary environment variables and secrets for RAS Batch.
  build.gradle
  charts/am-role-assignment-batch-service/Chart.yaml
  charts/am-role-assignment-batch-service/requirements.yaml
  charts/am-role-assignment-batch-service/values.preview.template.yaml
  charts/am-role-assignment-batch-service/values.yaml
  liquibase.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/roleassignmentbatch/EmptyFunctionalTest.java
  src/integrationTest/resources/bootstrap.yaml
  src/integrationTest/resources/db/changelog/db.changelog-master.xml
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplication.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
  src/main/resources/application.yaml
  src/main/resources/db/changelog/db.changelog-AM-1029.xml
  src/main/resources/db/changelog/db.changelog-AM-1060.xml
  src/main/resources/db/changelog/db.changelog-AM-823.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/liquibase.properties
  src/smokeTest/java/uk/gov/hmcts/reform/roleassignmentbatch/EmptySmokeTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-14

#18 Upgrading the dependency check plugin.
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-18

#19 Updating the liquibase scripts.
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplication.java
  src/main/resources/db/changelog/db.changelog-AM-1029.xml
  src/main/resources/db/changelog/db.changelog-AM-1029_3.xml
  src/main/resources/db/changelog/db.changelog-AM-1042_4.xml
  src/main/resources/db/changelog/db.changelog-AM-1060_2.xml
  src/main/resources/db/changelog/db.changelog-AM-1068_5.xml
  src/main/resources/db/changelog/db.changelog-AM-823_1.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-19
