Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2021-06, with the labels that each got.

#32 Added the dependbot.
  .github/dependabot.yml
  .github/stale.yml
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-32

#69 Updating the batch size.
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-69

#77 Add github autoupdate
  .github/workflows/autoupdate.yml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-77
