Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2022-01, with the labels that each got.

#185 Update fortify release id
  Jenkinsfile_CNP
  Jenkinsfile_nightly_disabled
  config/fortify-client.properties
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-185

#207 Enable nightly build and implement fortify
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-207

#208 Add fortify client library reference
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-208

#209 updated the config as per fortify
  src/integrationTest/resources/application-test.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-209

#210 disabling the JBS tasklet
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-210

#211 Disable jbs integration
  build.gradle
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/BatchConfig.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/task/EmptyTask.java
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-211

#212 removed the JBS variable to avoid vault mounting issue
  charts/am-role-assignment-batch-service/Chart.yaml
  charts/am-role-assignment-batch-service/values.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-212

#224 Removing jcenter
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-224
