Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2022-09, with the labels that each got.

#430 AM-2343 Suppressing LD SnakeYaml CVE
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-430

#441 Suppress new versions of SnakeYaml CVE
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-441

#444 expiry records deletion for JBS
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-444

#451 2380_CVE
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-451

#460 Suppressing snakeyaml additional CVE
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-460
