Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2022-04, with the labels that each got.

#270 Updated postgresql dependency
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-270

#283 CVE fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-283

#286 CVE fix 21 04 ras batch
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-286

#292 cve suppress
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-292
