Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2022-08, with the labels that each got.

#396 RAS:BatchMerge renovate bot pr's
  build.gradle
  infrastructure/terraform.tf
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-396

#408 RAS Batch:combine renovate PR's
  build.gradle
  infrastructure/.terraform-version
Labels: ns:am, prd:am, no-changes, rel:am-role-assignment-batch-service-pr-408

#421 Add backstage configuration file
  catalog-info.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-421
