Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2022-05, with the labels that each got.

#294 AM-2137: Upgrading to Java 17
  Dockerfile
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-294

#325 Update combine-prs.yml
  .github/workflows/combine-prs.yml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-325

#330 Delete dependabot.yml
  .github/dependabot.yml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-330

#336 CVE-2016-1000027 suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-336
