Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2023-07, with the labels that each got.

#720 AM-2846: For preview pipelines enable cleanup of helm releases
  Jenkinsfile_CNP
Labels: ns:am, prd:am, keep-helm, rel:am-role-assignment-batch-service-pr-720

#714 AM-2823-CVE-2023-20883 FIX
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-714

#721 AM-2852 CVE-2023-34981 tomcat upgrade 9.0.76
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-721

#723 AM-2728 CVE-2022-1471 snakeyaml 2.0
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-723

#724 AM-2728 AM-2860 Remove Github Autoupdate
  .github/workflows/autoupdate.yml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-724

#727 AM-2851 CVE-2023-2976 guava 32.0.1-jre,suppression removed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-727

#745 AM-2890 CVE-2023-38286 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-745
