Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2023-02, with the labels that each got.

#608 Dependency Check
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-608

#616 infra depricate update
  infrastructure/variables.tf
Labels: ns:am, prd:am, no-changes, rel:am-role-assignment-batch-service-pr-616

#620 Springboot upgrade 2.7.7
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/resources/application-test.yaml
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-620

#632 Update Chart.yaml
  charts/am-role-assignment-batch-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-632

#653 RAS Batch:Application Nightly build failed due to CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-653
