Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2023-06, with the labels that each got.

#713 AM-2823-CVE-2023-20883 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-713

#717 AM-2839 CVE-2023-35116 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-717

#719 AM-2851 CVE-2023-2976 and AM-2852 CVE-2023-34981 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-719

#716 AM-2776 CVE-2023-20863 spring framework upgrade 5.3.27
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-716
