Repository hmcts/am-role-assignment-batch-service, pull requests merged in 2023-05, with the labels that each got.

#703 AM-2786 CVE-2023-20873 AM-2787 CVE-2023-20862 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-703

#689 AM 2750
  .gitignore
  Dockerfile
  build.gradle
  charts/am-role-assignment-batch-service/Chart.yaml
  charts/am-role-assignment-batch-service/values.preview.template.yaml
  charts/am-role-assignment-batch-service/values.yaml
  lib/AI-Agent.xml
  lib/applicationinsights-agent-2.4.1.jar
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/RoleAssignmentBatchApplication.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentbatch/config/AppInsightsConfig.java
  web.config
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-689

#708 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-708

#709 nightly cron timing corrected
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-709

#710 AM-2816 CVE-2023-28709 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-710

#712 AM-2806: Upgrade chart-job version
  charts/am-role-assignment-batch-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-712

#711 AM-2816 CVE-2023-28709 tomcat version upgraded to 9.0.74
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-batch-service-pr-711
